# Generated by Django 5.0.7 on 2024-07-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('review', models.CharField(default='', max_length=350)),
                ('priority', models.BooleanField(default=False)),
                ('review_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
