# Generated by Django 5.0.7 on 2024-07-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
