# Generated by Django 5.0.7 on 2024-07-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_review_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='file',
        ),
    ]
