# Generated by Django 5.0.7 on 2024-07-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_remove_review_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_submitted',
        ),
    ]
