# Generated by Django 5.0.7 on 2024-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_remove_review_review_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(default='', max_length=30, unique=True)),
                ('recipe', models.TextField(default='')),
            ],
        ),
    ]
