# Generated by Django 5.0.7 on 2024-07-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('VEG', 'Vegetarian'), ('PESC', 'Pescatarian'), ('MEAT', 'Meat Eaters')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
