# Generated by Django 5.0.7 on 2024-07-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_remove_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images/'),
        ),
    ]
