# Generated by Django 5.0.7 on 2024-07-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
    ]
